run:
  timeout: 10m
  skip-files:
    - "zz_generated.*.go"

linters-settings:
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true

  lll:
    line-length: 150
    
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/layer3automation)
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      # Conflicts with govet check-shadowing
      - sloppyReassign
  goimports:
    local-prefixes: github.com/liqotech
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: true
    require-specific: true
  dupl:
    threshold: 300

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gci
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:

  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-use-default: false
  exclude:
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked

  exclude-rules:
    - linters:
        - govet
      text: 'declaration of "(err|ctx)" shadows declaration at'
    - linters:
        - gosec
      text: TLS InsecureSkipVerify set true.
    - linters:
        - errorlint
      text: type switch on error will fail on wrapped errors. Use errors.As to check for specific errors

    - path: _test\.go
      linters:
        - whitespace